### ISSUE TITLE
Aucun retour

### ISSUE THREAD

**Issue by Desaydrone** [JDureau/snips-skill-meteo#3]
Bonjour,

J'ai installé via Sam votre skill pour snips, tout c'est bien passé, la demande de clef api et de ville à été fait le fichier de config contient bien les bonne valeur.

Par contre que je fais une demande de météo snips comprend bien ma question, semble lancer votre script mais aucun retour,

Et dans le syslog voila ce que je peux constater

`Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err] Traceback (most recent call last):

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]   File "_ctypes/callbacks.c", line 315, in 'calling callback function' 

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]   File "/var/lib/snips/skills/snips-skill-meteo/venv/local/lib/python2.7/site-packages/hermes_python/hermes.py", line 55, in called_with_good_params

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]     return func(self, *parsed_args)

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]   File "./action-meteo.py", line 231, in intent_received

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]     hermes.publish_end_session(intent_message.session_id, sentence)

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]   File "/var/lib/snips/skills/snips-skill-meteo/venv/local/lib/python2.7/site-packages/hermes_python/hermes.py", line 170, in publish_end_session

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]     cEndSessionMessage = CEndSessionMessage.build(session_id, text)

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]   File "/var/lib/snips/skills/snips-skill-meteo/venv/local/lib/python2.7/site-packages/hermes_python/ffi/ontology.py", line 64, in build

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err]     return cls(session_id.encode('utf-8'), text.encode('utf-8')) 

Oct  8 06:41:29 raspberrypi snips-skill-server[16118]: INFO:snips_skill_server_lib::runner: [meteo][err] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
`

Je ne sais pas si ça peut avoir une réel incidence ?

**Comment by Charlo26** [comment]
Bonjour, j'ai le même problème et oui, c'est pour ça que vous n'avez aucun retour
pour régler le problème il faut aller modifié le fichier action-meteo.py

- /var/lib/snips/skills/snips-skill-meteo/action-meteo.py

y ajouter après la liste des import : 

```
import sys  

reload(sys)  
sys.setdefaultencoding('utf8')
```

Voilà j'espère que ça va marcher pour vous.
